### ISSUE TITLE
Is a separate loader needed after react-hot-loader 1.0?

### ISSUE THREAD

**Issue by gaearon** [omniscientjs/omniscient-react-hot-loader#6]
[React Hot Loader 1.0 ditches parsing source files](https://github.com/gaearon/react-hot-loader/tree/master/docs#migrating-to-10) and instead makes `module.exports` hot by default, as well as all its own properties.

To opt-in any class that is not exported to hot reload, there is a new `module.makeHot` API.

Since we no longer parse `React.createClass`, is a separate loader for OmniscientJS now necessary?

**Comment by torgeir** [comment]
@gaearon sorry this took me so long! I'm guessing you already knew this, but I've just confirmed your expectations - the new hot loader works flawlessly with omniscient without touching any other code than the webpack config :beers:

I've yet to clean out this repo for a minimal setup on how to get things working, but in the mean time here's one with hot reloading enabled https://github.com/torgeir/scales

**Comment by gaearon** [comment]
:+1:

**Comment by torgeir** [comment]
Updated the example! https://github.com/omniscientjs/omniscient-react-hot-loader
